# Generated by Django 4.2.2 on 2023-07-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryApiApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylist',
            name='name',
            field=models.CharField(default='Test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='food',
            field=models.CharField(),
        ),
    ]
